"""create relationship

Revision ID: df5a7d549a77
Revises: c6a9705b17f2
Create Date: 2024-03-27 16:41:21.495247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5a7d549a77'
down_revision: Union[str, None] = 'c6a9705b17f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=32), nullable=False))
    op.drop_constraint('user_phoneNumber_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['phone'])
    op.drop_column('user', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phoneNumber', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_phoneNumber_key', 'user', ['phoneNumber'])
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
