"""create relationship

Revision ID: aaaa78879cf7
Revises: df5a7d549a77
Create Date: 2024-03-27 20:07:17.098691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaa78879cf7'
down_revision: Union[str, None] = 'df5a7d549a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bio'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('password', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=32), nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    op.drop_table('profile')
    # ### end Alembic commands ###
