"""create relationship

Revision ID: c6a9705b17f2
Revises: 4304b7eedf26
Create Date: 2024-03-27 15:31:10.786339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a9705b17f2'
down_revision: Union[str, None] = '4304b7eedf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'phoneNumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phoneNumber',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
